steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/athena-ai', '-f', 'deployment/Dockerfile', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/athena-ai']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'athena-ai'
      - '--image'
      - 'gcr.io/$PROJECT_ID/athena-ai'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '1'
      - '--port'
      - '8000'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,LOG_LEVEL=INFO'
      - '--set-secrets'
      - 'CDP_API_KEY_ID=cdp-api-key:latest,CDP_API_KEY_SECRET=cdp-api-secret:latest,CDP_CLIENT_API_KEY=cdp-client-api-key:latest,GOOGLE_API_KEY=google-api-key:latest,MEM0_API_KEY=mem0-api-key:latest,LANGSMITH_API_KEY=langsmith-api-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/athena-ai'

timeout: '1200s'