version: '3.8'

services:
  athena:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CDP_API_KEY=${CDP_API_KEY}
      - CDP_API_SECRET=${CDP_API_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - MEM0_API_KEY=${MEM0_API_KEY}
      - BASE_RPC_URL=${BASE_RPC_URL:-https://mainnet.base.org}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
    restart: unless-stopped
    networks:
      - athena-network
    depends_on:
      - redis
      - qdrant

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - athena-network

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped
    networks:
      - athena-network

networks:
  athena-network:
    driver: bridge

volumes:
  redis-data:
  qdrant-data: