version: '3.8'

services:
  athena-agent:
    build: .
    container_name: athena-agent
    restart: unless-stopped
    environment:
      - ENV=development
      - LOG_LEVEL=INFO
    env_file:
      - .env
    volumes:
      - ./wallet_data:/app/wallet_data
      - ./logs:/app/logs
      - ${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}:ro
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - athena-network

  # Optional: Local monitoring with Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: athena-prometheus
    restart: unless-stopped
    volumes:
      - ./deployment/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - athena-network

  # Optional: Grafana for dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: athena-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - athena-network

networks:
  athena-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: