name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  basic-security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install bandit safety pip-audit
    
    - name: Run Bandit (Python security linter)
      run: |
        # Continue on error to see all issues
        bandit -r src/ -ll -i -x '*test*' || echo "Bandit found some issues"
    
    - name: Check for secrets
      run: |
        # Basic check for hardcoded secrets
        echo "Checking for potential secrets..."
        ! grep -r "sk-[a-zA-Z0-9]" src/ || echo "No OpenAI keys found"
        ! grep -r "AKIA[A-Z0-9]" src/ || echo "No AWS keys found"
        ! grep -r "-----BEGIN" src/ || echo "No private keys found"
    
    - name: Dependency vulnerability scan
      run: |
        # Run pip-audit but don't fail the build
        pip-audit || echo "Some vulnerabilities found, but continuing"
    
    - name: License check
      run: |
        pip install pip-licenses
        echo "## License Report" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        pip-licenses --format=plain-vertical --with-authors --order=license >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
    
    - name: Security Summary
      if: always()
      run: |
        echo "## Security Scan Complete" >> $GITHUB_STEP_SUMMARY
        echo "Basic security checks have been performed." >> $GITHUB_STEP_SUMMARY
        echo "For production deployment, consider:" >> $GITHUB_STEP_SUMMARY
        echo "- Setting up GitHub Secret Scanning" >> $GITHUB_STEP_SUMMARY
        echo "- Enabling Dependabot alerts" >> $GITHUB_STEP_SUMMARY
        echo "- Adding SAST/DAST tools" >> $GITHUB_STEP_SUMMARY